theme = "bli"
languageCode = "en-US"
baseurl = "https://youth.grii-bsd.org"
defaultContentLanguage = "en"

[languages]
  [languages.en]
    contentDir = "content/english"
    languageName = "English"
    title = "Youth GRII BSD"

  [languages.id]
    contentDir = "content/indonesian"
    languageName = "Bahasa Indonesia"
    title = "Pemuda GRII BSD"

[params]
  description = "Youth GRII BSD"
  name = "Youth GRII BSD"
  
  darkModeToggle = true
  enableSearch = false
  favicon = "/favicon.ico"

  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-yellow-200"

  heading = "We are Youth GRII BSD"
  subheading = "Come join us for fellowship. Every Saturday 4:45pm."
  socialTitle = "Follow us!"
  socialDescription = "Find us on our social media here:"
  morePosts = "More Posts"
  photos = [
    "/cover1.jpeg",
    "/cover2.jpeg",
    "/cover3.jpeg",
    "/cover4.jpeg",
  ]

[params.id]
  heading = "Kami adalah Pemuda GRII BSD"
  subheading = "Ayo bersekutu bersama dengan kami. Setiap Sabtu, jam 16:45."
  socialTitle = "Ikuti kami!"
  socialDescription = "Cari kami di media sosial melalui tautan berikut:"
  morePosts = "Acara Berikutnya"

[params.homepage.social]
  instagram = "https://instagram.com/youthgriibsd"
  youtube = "https://www.youtube.com/channel/UCUSYXuRT8Epm_V5294Mp6Ug"
  email = "mailto:youthgriibsd@gmail.com"

[build]
  writeStats = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    unsafe = true

[[languages.en.menu.main]]
  name = "Contact"
  weight = 20
  url = "/contact"

[[languages.en.menu.main]]
  name = "Offering"
  weight = 10
  url = "/offering"

[[languages.id.menu.main]]
  identifier = "kontak"
  name = "Kontak"
  weight = 20
  url = "/id/kontak"

[[languages.id.menu.main]]
  identifier = "persembahan"
  name = "Persembahan"
  weight = 10
  url = "/id/persembahan"

